TexnoGallery/Areas/Admin/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TexnoGallery.Models;

namespace TexnoGallery.Areas.Admin.Controllers
{
    public class AdminAccountController : Controller
    {
        texnoEntities db = new texnoEntities();
        
        public ActionResult Login()
        {
            return View();
        }
        // GET: Admin/AdminAccount
        [HttpPost]
        public ActionResult Login(string email, string password)
        {
            if(email!=string.Empty && password != string.Empty)
            {
                AdminsTB selectAdmin = db.AdminsTB.Find(1);
                if(selectAdmin.Email==email && selectAdmin.Password==password)
                {
                    Session["adminLogged"] = selectAdmin;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Email və ya Parol səhvdir!";
                }
                
            }
            else
            {
                ViewBag.Error = "Zəhmət olmasa bütün xanaları doldurun!";
            }

            return View();
        }
    }
}

TexnoGallery/Areas/Admin/Views/AdminAccount/Login.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from admin.pixelstrap.com/endless/ltr/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Jul 2019 09:09:55 GMT -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="endless admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, endless admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="../assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="../assets/images/favicon.png" type="image/x-icon">
    <title>Texno Gallery</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/fontawesome.css">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/icofont.css">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/themify.css">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/flag-icon.css">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/feather-icon.css">
    <!-- Plugins css start-->
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/style.css">
    <link id="color" rel="stylesheet" href="~/Areas/Admin/assets/css/light-1.css" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/assets/css/responsive.css">
</head>
<body style="background-image:url(../Uploads/1hC8U.jpg)">
    <!-- Loader starts-->
    <div class="loader-wrapper">
        <div class="loader bg-white">
            <div class="whirly-loader"> </div>
        </div>
    </div>
    <!-- Loader ends-->
    <!-- page-wrapper Start-->
    <div class="page-wrapper">
        <div class="container-fluid p-0">
            <!-- login page start-->
            <div class="authentication-main">
                <div class="row">
                    <div class="col-md-12">
                        <div class="auth-innerright">
                            <div class="authentication-box">

                                <div class="card mt-4 bg-dark">
                                    <div class="card-body">
                                        <div class="text-center">
                                            <div class="text-center"><img style="width:200px" src="~/images/albaba.png" alt=""></div>
                                            <h5 class="text-white mt-5">LOGIN</h5>

                                        </div>
                                        <form class="theme-form" method="post" action="@Url.Action("Login","AdminAccount")">
                                            <div class="form-group">
                                                <label class="col-form-label pt-0">Your Name</label>
                                                <input class="form-control" type="text" name="email" required="">
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label">Password</label>
                                                <input class="form-control" name="password" type="password" required="">
                                            </div>

                                            <div class="form-group form-row mt-4 mb-0">
                                                <button class="btn btn-primary btn-block" type="submit">Login</button>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- login page end-->
        </div>
    </div>
    <!-- latest jquery-->
    <script src="~/Areas/Admin/assets/js/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap js-->
    <script src="~/Areas/Admin/assets/js/bootstrap/popper.min.js"></script>
    <script src="~/Areas/Admin/assets/js/bootstrap/bootstrap.js"></script>
    <!-- feather icon js-->
    <script src="~/Areas/Admin/assets/js/icons/feather-icon/feather.min.js"></script>
    <script src="~/Areas/Admin/assets/js/icons/feather-icon/feather-icon.js"></script>
    <!-- Sidebar jquery-->
    <script src="~/Areas/Admin/assets/js/sidebar-menu.js"></script>
    <script src="~/Areas/Admin/assets/js/config.js"></script>
    <!-- Plugins JS start-->
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="~/Areas/Admin/assets/js/script.js"></script>
    <!-- Plugin used-->
</body>

<!-- Mirrored from admin.pixelstrap.com/endless/ltr/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Jul 2019 09:09:55 GMT -->
</html>