TexnoGallery/Areas/Admin/Controllers/SlideImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TexnoGallery.Models;

namespace TexnoGallery.Areas.Admin.Controllers
{
    public class SlideImageController : Controller
    {
        private texnoEntities db = new texnoEntities();

        // GET: Admin/SlideImage
        public ActionResult Index()
        {
            return View(db.Slide.ToList());
        }


       

        // GET: Admin/SlideImage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SlideImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SlideImg")] Slide slide, HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {   
                    WebImage image = new WebImage(Photo.InputStream);
                    FileInfo photoInfo = new FileInfo(Photo.FileName);
                    string newPhoto = Guid.NewGuid().ToString() + photoInfo.Extension;
                    image.Save("~/Uploads/ProjectImage/" + newPhoto);
                    slide.SlideImg = "/Uploads/ProjectImage/" + newPhoto;
                }
                db.Slide.Add(slide);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slide);
        }

        // GET: Admin/SlideImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slide.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Admin/SlideImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,[Bind(Include = "Id,SlideImg")] Slide slide,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                Slide selected = db.Slide.SingleOrDefault(nt => nt.Id == id);
                if (Photo != null)
                {
                    
                    WebImage image = new WebImage(Photo.InputStream);
                    FileInfo photoInfo = new FileInfo(Photo.FileName);
                    string newPhoto = Guid.NewGuid().ToString() + photoInfo;
                    image.Save("~/Uploads/ProjectImage/" + newPhoto);
                    slide.SlideImg = "/Uploads/ProjectImage/" + newPhoto;
                }
                selected.SlideImg = slide.SlideImg;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        // GET: Admin/SlideImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slide.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Admin/SlideImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slide slide = db.Slide.Find(id);
            db.Slide.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);

        }
        
    }
}

TexnoGallery/Areas/Admin/Views/SlideImage/Create.cshtml
@model TexnoGallery.Models.Slide

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="text-center mt-3">Create</h2>

@using (Html.BeginForm("Create","SlideImage",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           
            <div class="col-md-10">
                <input type="file" name="Photo" id="Photo" accept=".jpg,.png,.jpeg,.svg" />
                @Html.ValidationMessageFor(model => model.SlideImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to the list", "Index")
</div>

TexnoGallery/Areas/Admin/Views/SlideImage/Delete.cshtml
@model TexnoGallery.Models.Slide

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="text-center mt-3">Delete</h2>

<h3 class="mt-2">Are you sure you want to delete this picture?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
    

        <dd>
            <img src="@Model.SlideImg" class="img-thumbnail" style="width:25%"/>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TexnoGallery/Areas/Admin/Views/SlideImage/Edit.cshtml
@model TexnoGallery.Models.Slide

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="text-center mt-3">Edit</h2>

@using (Html.BeginForm("Edit","SlideImage",FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
           
            <div class="col-md-10">
                <input type="file" name="Photo" id="Photo" accept=".jpg,.png,.jpeg,.svg" />
                @Html.ValidationMessageFor(model => model.SlideImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to the list", "Index")
</div>

TexnoGallery/Areas/Admin/Views/SlideImage/Index.cshtml
@model IEnumerable<TexnoGallery.Models.Slide>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="text-center mt-3">Slide</h2>

<span class="text-right mr-3 mb-5" style="font-size:15px;">
    <a style="padding:10px 15px;background-color:brown; border-radius:5px; color:white" href=@Url.Action("Create","SlideImage")>Add a new photo</a>
   
</span>
<table class="table">


@foreach (var item in Model) {
    <tr>
        <td>
           <img  src="@item.SlideImg" class="img-thumbnail" style="width:25%"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>